###################
## HAMAC Routine ##
###################

## Loads GPS and ACT data from files generated by GPS plus X in a directory
## A. SCRIBAN & ChatGPT - Janvier 2024

### Libraries

### Paths
inDir <- "./0_RawData"
outDir <- "./1_IntermeData"
filesPrefix <- "/HAMAC-SN-"

### Functions
# Concatenates CSV files with a specific prefix
concatenate_csv_files <- function(directory, prefix, nbCol) {
  # Get the list of files with the specified prefix
  files <- list.files(directory, pattern = paste0("^", prefix, ".*\\.csv$"), recursive = TRUE, full.names = TRUE)

  # Initialize an empty data frame
  concatenated_data <- data.frame()

  # Loop through each file and concatenate data
  for (file in files) {
    # Read CSV file

    current_data <- read.csv(file,sep=";",header=F, skip=1,na.strings = "NA")
    cat(file, ncol(current_data),"\n")

    if (prefix == "GPS_" & ncol(current_data) == (nbCol - 2)) {
      current_data <- cbind(current_data, V51 = NA, V52 = NA)
    }

    # Concatenate data
    concatenated_data <- rbind(concatenated_data, current_data)
  }

  return(concatenated_data)
}

### Execution
## GPS
# Concatenate files starting with "GPS-"
gps_table <- concatenate_csv_files(inDir, "GPS_", 52)

cat("\nGPS Table:\n")
print(head(gps_table))

#### Intermediate data save
# Sauvegarde en CSV
write.table(gps_table, paste0(outDir, filesPrefix, "GPS_WholeDir.csv"), sep=";",  row.names=FALSE)

GPSACQorig <- gps_table
# Transition to HAMAC-SN-GPS_Data_Prep.R

## ACT
# Concatenate files starting with "ACT-"
act_table <- concatenate_csv_files(inDir, "ACT_", 17)

# Print the first few rows of each table
cat("ACT Table:\n")
print(head(act_table))

# Sauvegarde en CSV
write.table(act_table, paste0(outDir, filesPrefix, "ACT_WholeDir.csv"),sep=";", row.names=FALSE)

ACTACQorig <- act_table
# Transition to HAMAC-SN-GPS_Data_Prep.R

rm(gps_table, act_table)
